### ISSUE TITLE
can't fetch with browser

### ISSUE THREAD

**Issue by btk** [incebellipipo/apitizer#2]
We need to add a wildcard cors policy.

`.send_header("Access-Control-Allow-Origin", "*")`

currently only curl requests are allowed.

Maybe [this ](https://gist.github.com/enjalot/2904124) would be helpful

**Comment by incebellipipo** [comment]
I'm not an expert on web development, however as I now, I can enable CORS by using flask_cors package. I'm not sure if it is safe to enable for security manners. I guess it is open to debate and enabling it depends on the problem that it posses. 

Simple curl request is not throws an error about cross origin updates.
```
$ curl https://covid19gunlukleri.com/api/
```

Also, I updated the application just a few hours ago. May be the cause of the problem could be the temporarily offline service?

**Comment by incebellipipo** [comment]
I'll enable CORS anyway :D, will close this issue when relative commit is pushed

**Comment by btk** [comment]
Since this api is read only, there is no harm to enable it :)

**Comment by Cihatata** [comment]
I'm trying to fetch data with axios  but i getting Cross-Origin Request Blocked.

**Comment by btk** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/5216601/78129452-4db98200-7420-11ea-9616-101abc0a4fd6.png)

`/all` works but today one doesn't for xmlhttprequests

**Comment by incebellipipo** [comment]
I enabled CORS within flask and disabled it again couse it didn't work with CORS enabled. idk why.
https://github.com/incebellipipo/apitizer/blob/a8d1388ac1fb0be31b29613238d1e02166259b69/apitizer/web_service.py#L11

![image](https://user-images.githubusercontent.com/9779011/78130531-25328780-7422-11ea-8b8e-d32340a87797.png)

I also have enabled CORS in nginx config but i guess  its related with my url rewrite rule.

**Comment by incebellipipo** [comment]
90535f0271b8126e8966c45953e7273c964c1e14 fixed it. `all` route existed but `all/` is not. If you guys also confirm this, i'll close this issue.

**Comment by btk** [comment]
both works
